# Generated by Django 4.1.4 on 2023-09-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_roommember_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='Uid',
            new_name='uid',
        ),
    ]
